[2025-02-22 11:05:40,095] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2025-02-22 11:05:40,100] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2025-02-22 11:05:40,100] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:05:40,100] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:05:40,100] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:05:40,120] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_into_db> on 2024-03-20 00:00:00+00:00
[2025-02-22 11:05:40,124] {standard_task_runner.py:52} INFO - Started process 51469 to run task
[2025-02-22 11:05:40,127] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'load_data_into_db', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmp1w5pxpr7', '--error-file', '/tmp/tmpu_9uk1mq']
[2025-02-22 11:05:40,127] {standard_task_runner.py:80} INFO - Job 133: Subtask load_data_into_db
[2025-02-22 11:05:40,174] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-03-20T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:05:40,244] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=load_data_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-03-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-20T00:00:00+00:00
[2025-02-22 11:05:40,245] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:05:40,245] {logging_mixin.py:115} INFO - Error: /workspace/Assignment/01_data_pipeline/scripts/data/leadscoring.csv not found!
[2025-02-22 11:05:40,245] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:05:40,250] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=load_data_into_db, execution_date=20240320T000000, start_date=20250222T110540, end_date=20250222T110540
[2025-02-22 11:05:40,299] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:05:40,448] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
