[2025-02-22 11:28:35,580] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2025-02-22 11:28:35,584] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2025-02-22 11:28:35,585] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:28:35,585] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:28:35,585] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:28:35,607] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_into_db> on 2024-09-01 00:00:00+00:00
[2025-02-22 11:28:35,612] {standard_task_runner.py:52} INFO - Started process 65867 to run task
[2025-02-22 11:28:35,614] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'load_data_into_db', 'scheduled__2024-09-01T00:00:00+00:00', '--job-id', '795', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmpdp5exhdj', '--error-file', '/tmp/tmpkw638zo2']
[2025-02-22 11:28:35,615] {standard_task_runner.py:80} INFO - Job 795: Subtask load_data_into_db
[2025-02-22 11:28:35,656] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-09-01T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:28:35,726] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=load_data_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-01T00:00:00+00:00
[2025-02-22 11:28:35,726] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:28:35,726] {logging_mixin.py:115} INFO - Error: /workspace/Assignment/01_data_pipeline/scripts/data/leadscoring.csv not found!
[2025-02-22 11:28:35,726] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:28:35,731] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=load_data_into_db, execution_date=20240901T000000, start_date=20250222T112835, end_date=20250222T112835
[2025-02-22 11:28:35,786] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:28:35,841] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
