[2025-02-22 11:01:44,152] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-02-25T00:00:00+00:00 [queued]>
[2025-02-22 11:01:44,159] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-02-25T00:00:00+00:00 [queued]>
[2025-02-22 11:01:44,159] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:01:44,159] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:01:44,159] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:01:44,259] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_into_db> on 2024-02-25 00:00:00+00:00
[2025-02-22 11:01:44,266] {standard_task_runner.py:52} INFO - Started process 49355 to run task
[2025-02-22 11:01:44,269] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'load_data_into_db', 'scheduled__2024-02-25T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmprrfiw3ht', '--error-file', '/tmp/tmpnhbnbbb2']
[2025-02-22 11:01:44,270] {standard_task_runner.py:80} INFO - Job 37: Subtask load_data_into_db
[2025-02-22 11:01:44,410] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-02-25T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:01:44,724] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=load_data_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-02-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-25T00:00:00+00:00
[2025-02-22 11:01:44,726] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:01:44,727] {logging_mixin.py:115} INFO - Error: /workspace/Assignment/01_data_pipeline/scripts/data/leadscoring.csv not found!
[2025-02-22 11:01:44,727] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:01:44,742] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=load_data_into_db, execution_date=20240225T000000, start_date=20250222T110144, end_date=20250222T110144
[2025-02-22 11:01:45,004] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:01:45,309] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
