[2025-02-22 11:19:17,320] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_categorical_vars scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2025-02-22 11:19:17,325] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_categorical_vars scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2025-02-22 11:19:17,325] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:19:17,325] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:19:17,325] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:19:17,344] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): map_categorical_vars> on 2024-06-23 00:00:00+00:00
[2025-02-22 11:19:17,348] {standard_task_runner.py:52} INFO - Started process 59997 to run task
[2025-02-22 11:19:17,350] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'map_categorical_vars', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmpw2hhxefs', '--error-file', '/tmp/tmpos5t9yn7']
[2025-02-22 11:19:17,351] {standard_task_runner.py:80} INFO - Job 522: Subtask map_categorical_vars
[2025-02-22 11:19:17,393] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.map_categorical_vars scheduled__2024-06-23T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:19:17,469] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=map_categorical_vars
AIRFLOW_CTX_EXECUTION_DATE=2024-06-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-23T00:00:00+00:00
[2025-02-22 11:19:17,470] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:19:17,470] {logging_mixin.py:115} INFO - Error in mapping categorical variables: unable to open database file
[2025-02-22 11:19:17,470] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:19:17,474] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=map_categorical_vars, execution_date=20240623T000000, start_date=20250222T111917, end_date=20250222T111917
[2025-02-22 11:19:17,522] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:19:17,548] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
