[2025-02-22 11:00:27,432] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db manual__2025-02-22T10:57:08+00:00 [queued]>
[2025-02-22 11:00:27,438] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db manual__2025-02-22T10:57:08+00:00 [queued]>
[2025-02-22 11:00:27,438] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:00:27,438] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:00:27,438] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:00:27,529] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_into_db> on 2025-02-22 10:57:08+00:00
[2025-02-22 11:00:27,535] {standard_task_runner.py:52} INFO - Started process 48753 to run task
[2025-02-22 11:00:27,538] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'load_data_into_db', 'manual__2025-02-22T10:57:08+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmpexvx_igv', '--error-file', '/tmp/tmp8whqmloz']
[2025-02-22 11:00:27,539] {standard_task_runner.py:80} INFO - Job 12: Subtask load_data_into_db
[2025-02-22 11:00:27,730] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.load_data_into_db manual__2025-02-22T10:57:08+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:00:27,973] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=load_data_into_db
AIRFLOW_CTX_EXECUTION_DATE=2025-02-22T10:57:08+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-22T10:57:08+00:00
[2025-02-22 11:00:27,975] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:00:27,975] {logging_mixin.py:115} INFO - Error: /workspace/Assignment/01_data_pipeline/scripts/data/leadscoring.csv not found!
[2025-02-22 11:00:27,976] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:00:27,991] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=load_data_into_db, execution_date=20250222T105708, start_date=20250222T110027, end_date=20250222T110027
[2025-02-22 11:00:28,112] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:00:28,262] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
