[2025-02-22 11:40:54,358] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_categorical_vars scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2025-02-22 11:40:54,363] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_categorical_vars scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2025-02-22 11:40:54,363] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:40:54,363] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:40:54,363] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:40:54,434] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): map_categorical_vars> on 2024-11-28 00:00:00+00:00
[2025-02-22 11:40:54,438] {standard_task_runner.py:52} INFO - Started process 73559 to run task
[2025-02-22 11:40:54,441] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'map_categorical_vars', 'scheduled__2024-11-28T00:00:00+00:00', '--job-id', '1156', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmppdvtk8q4', '--error-file', '/tmp/tmp0i0rl3q9']
[2025-02-22 11:40:54,441] {standard_task_runner.py:80} INFO - Job 1156: Subtask map_categorical_vars
[2025-02-22 11:40:54,510] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.map_categorical_vars scheduled__2024-11-28T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:40:54,625] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=map_categorical_vars
AIRFLOW_CTX_EXECUTION_DATE=2024-11-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-28T00:00:00+00:00
[2025-02-22 11:40:54,626] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:40:54,627] {logging_mixin.py:115} INFO - Error in mapping categorical variables: unable to open database file
[2025-02-22 11:40:54,627] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:40:54,635] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=map_categorical_vars, execution_date=20241128T000000, start_date=20250222T114054, end_date=20250222T114054
[2025-02-22 11:40:54,693] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:40:54,735] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
