[2025-02-22 11:42:25,683] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_categorical_vars scheduled__2024-12-07T00:00:00+00:00 [queued]>
[2025-02-22 11:42:25,688] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_categorical_vars scheduled__2024-12-07T00:00:00+00:00 [queued]>
[2025-02-22 11:42:25,688] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:42:25,688] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:42:25,688] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:42:25,946] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): map_categorical_vars> on 2024-12-07 00:00:00+00:00
[2025-02-22 11:42:25,952] {standard_task_runner.py:52} INFO - Started process 74345 to run task
[2025-02-22 11:42:25,954] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'map_categorical_vars', 'scheduled__2024-12-07T00:00:00+00:00', '--job-id', '1193', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmp_y3iyryc', '--error-file', '/tmp/tmpi3ifrpqe']
[2025-02-22 11:42:25,955] {standard_task_runner.py:80} INFO - Job 1193: Subtask map_categorical_vars
[2025-02-22 11:42:26,020] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.map_categorical_vars scheduled__2024-12-07T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:42:26,155] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=map_categorical_vars
AIRFLOW_CTX_EXECUTION_DATE=2024-12-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-07T00:00:00+00:00
[2025-02-22 11:42:26,156] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:42:26,156] {logging_mixin.py:115} INFO - Error in mapping categorical variables: unable to open database file
[2025-02-22 11:42:26,156] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:42:26,165] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=map_categorical_vars, execution_date=20241207T000000, start_date=20250222T114225, end_date=20250222T114226
[2025-02-22 11:42:26,207] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:42:26,249] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
