[2025-02-22 11:24:37,491] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-08-02T00:00:00+00:00 [queued]>
[2025-02-22 11:24:37,496] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-08-02T00:00:00+00:00 [queued]>
[2025-02-22 11:24:37,496] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:24:37,496] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:24:37,496] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:24:37,520] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_into_db> on 2024-08-02 00:00:00+00:00
[2025-02-22 11:24:37,524] {standard_task_runner.py:52} INFO - Started process 63384 to run task
[2025-02-22 11:24:37,527] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'load_data_into_db', 'scheduled__2024-08-02T00:00:00+00:00', '--job-id', '677', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmpb_5hiy1e', '--error-file', '/tmp/tmp8kkjk9yj']
[2025-02-22 11:24:37,528] {standard_task_runner.py:80} INFO - Job 677: Subtask load_data_into_db
[2025-02-22 11:24:37,594] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.load_data_into_db scheduled__2024-08-02T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:24:37,694] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=load_data_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-08-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-02T00:00:00+00:00
[2025-02-22 11:24:37,695] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:24:37,695] {logging_mixin.py:115} INFO - Error: /workspace/Assignment/01_data_pipeline/scripts/data/leadscoring.csv not found!
[2025-02-22 11:24:37,695] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:24:37,700] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=load_data_into_db, execution_date=20240802T000000, start_date=20250222T112437, end_date=20250222T112437
[2025-02-22 11:24:37,739] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:24:37,804] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
