[2025-02-22 11:01:07,300] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db manual__2025-02-22T11:00:34+00:00 [queued]>
[2025-02-22 11:01:07,305] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.load_data_into_db manual__2025-02-22T11:00:34+00:00 [queued]>
[2025-02-22 11:01:07,306] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:01:07,306] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:01:07,306] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:01:07,426] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_into_db> on 2025-02-22 11:00:34+00:00
[2025-02-22 11:01:07,433] {standard_task_runner.py:52} INFO - Started process 49055 to run task
[2025-02-22 11:01:07,436] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'load_data_into_db', 'manual__2025-02-22T11:00:34+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmp2c3whu0a', '--error-file', '/tmp/tmpkf3h6ml7']
[2025-02-22 11:01:07,437] {standard_task_runner.py:80} INFO - Job 25: Subtask load_data_into_db
[2025-02-22 11:01:07,565] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.load_data_into_db manual__2025-02-22T11:00:34+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:01:07,834] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=load_data_into_db
AIRFLOW_CTX_EXECUTION_DATE=2025-02-22T11:00:34+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-22T11:00:34+00:00
[2025-02-22 11:01:07,836] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:01:07,836] {logging_mixin.py:115} INFO - Error: /workspace/Assignment/01_data_pipeline/scripts/data/leadscoring.csv not found!
[2025-02-22 11:01:07,836] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:01:07,852] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=load_data_into_db, execution_date=20250222T110034, start_date=20250222T110107, end_date=20250222T110107
[2025-02-22 11:01:07,970] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:01:08,099] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
